#!/bin/bash
 
# Flushing all rules
iptables -F
iptables -X
 
# Setting default filter policy
iptables -P INPUT DROP
iptables -P OUTPUT DROP
iptables -P FORWARD DROP

# gmail
iptables -A OUTPUT -p tcp --dport 465 -j ACCEPT

# DNS
iptables -A OUTPUT -p tcp --dport 53 -j ACCEPT
iptables -A OUTPUT -p udp --dport 53 -j ACCEPT

# let any conection returning from estabilished outbound or related
# should solve smtp problem
iptables -A INPUT -m state --state RELATED,ESTABLISHED -j ACCEPT
iptables -A OUTPUT -m state --state ESTABLISHED,RELATED -j ACCEPT

# Allow unlimited traffic on loopback
iptables -A INPUT -i lo -j ACCEPT
iptables -A OUTPUT -o lo -j ACCEPT

# allow HTTP out (mostly for apt to be able to fetch updates)
iptables -A OUTPUT -p tcp --dport 80 -m state --state NEW,ESTABLISHED -j ACCEPT

# allow HTTPS out (mostly for apt to be able to fetch updates)
iptables -A OUTPUT -p tcp --dport 443 -m state --state NEW,ESTABLISHED -j ACCEPT

# log new SSH connections
iptables -A INPUT -p tcp --dport 22 --syn -j LOG --log-prefix "btcdSSH: "

# Allow incoming SSH
iptables -A INPUT -p tcp --dport 22 -m state --state NEW,ESTABLISHED -j ACCEPT
iptables -A OUTPUT -p tcp --sport 22 -m state --state ESTABLISHED -j ACCEPT
 
# Allow incoming 8333 *bitcoind*
iptables -A INPUT -p tcp --dport 8333 -m state --state NEW,ESTABLISHED -j ACCEPT
iptables -A OUTPUT -p tcp --sport 8333 -m state --state ESTABLISHED -j ACCEPT
 
# Allow outgoing 8333 *bitcoind*
iptables -A OUTPUT -p tcp --dport 8333 -m state --state NEW,ESTABLISHED -j ACCEPT
iptables -A INPUT -p tcp --sport 8333 -m state --state ESTABLISHED -j ACCEPT

# Allow incoming 9735 *lightningd*
iptables -A INPUT -p tcp --dport 9735 -m state --state NEW,ESTABLISHED -j ACCEPT
iptables -A OUTPUT -p tcp --sport 9735 -m state --state ESTABLISHED -j ACCEPT

# Allowing outgoing 9735 *lightningd*
iptables -A OUTPUT -p tcp --dport 9735 -m state --state NEW,ESTABLISHED -j ACCEPT
iptables -A INPUT -p tcp --sport 9735 -m state --state ESTABLISHED -j ACCEPT
